// GitHub API Functions
// Documentation: https://docs.github.com/en/rest
// Generated by VS Code Copilot, adapted for this project

/**
 * Fetch repositories from a GitHub user
 * @param {string} username - GitHub username
 * @param {string|Array} keywords - Keyword(s) to filter repositories
 * @returns {Promise<Array>} Array of repositories
 */
async function getRepositoriesByUser(username, keywords) {
  const baseUrl = `https://api.github.com/users/${username}/repos`;
  
  // Convert single keyword to array
  const keywordArray = Array.isArray(keywords) ? keywords : [keywords];
  
  try {
    const response = await fetch(`${baseUrl}?per_page=100&sort=updated&direction=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const repos = await response.json();
    console.log('GitHub user repositories response:', repos);
    
    // Filter repositories by keywords
    const filtered = repos.filter(repo => {
      const name = (repo.name || '').toLowerCase();
      const description = (repo.description || '').toLowerCase();
      const fullText = `${name} ${description}`;
      
      return keywordArray.some(keyword => 
        fullText.includes(keyword.toLowerCase())
      );
    });
    
    return filtered;
  } catch (error) {
    console.error('Error fetching user repositories from GitHub:', error);
    return [];
  }
}

/**
 * Search repositories by topic
 * @param {string} topic - Topic to search for
 * @param {number} limit - Maximum number of results
 * @returns {Promise<Array>} Array of repositories
 */
async function getRepositoriesByTopic(topic, limit = 100) {
  const baseUrl = 'https://api.github.com/search/repositories';
  const query = `topic:${topic.toLowerCase()}`;
  
  try {
    const response = await fetch(`${baseUrl}?q=${encodeURIComponent(query)}&per_page=${limit}&sort=stars&order=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('GitHub topic search response:', data);
    
    return data.items || [];
  } catch (error) {
    console.error('Error fetching repositories by topic from GitHub:', error);
    return [];
  }
}

/**
 * Search repositories in organization with topic
 * @param {string} org - Organization name
 * @param {string} topic - Topic to filter by
 * @param {number} limit - Maximum number of results
 * @returns {Promise<Array>} Array of repositories
 */
async function getOrganizationRepositoriesByTopic(org, topic, limit = 100) {
  const baseUrl = 'https://api.github.com/search/repositories';
  
  try {
    // Build query: org:orgname AND topic:topic
    const query = `org:${org} topic:${topic.toLowerCase()}`;
    console.log('Searching organization repositories with query:', query);
    
    const response = await fetch(`${baseUrl}?q=${encodeURIComponent(query)}&per_page=${limit}&sort=updated&order=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('GitHub organization + topic search response:', data);
    console.log('Number of results:', data.items ? data.items.length : 0);
    
    return data.items || [];
  } catch (error) {
    console.error('Error fetching organization repositories by topic:', error);
    return [];
  }
}

/**
 * Search repositories by user involvement AND topic
 * @param {string} username - GitHub username
 * @param {string} topic - Topic to filter by
 * @param {number} limit - Maximum number of results
 * @returns {Promise<Array>} Array of repositories
 */
async function getRepositoriesByInvolvementAndTopic(username, topic, limit = 100) {
  const baseUrl = 'https://api.github.com/search/repositories';
  
  try {
    // Try to search with involves: and topic:
    const query = `involves:${username} topic:${topic.toLowerCase()}`;
    console.log('Searching with query:', query);
    
    const response = await fetch(`${baseUrl}?q=${encodeURIComponent(query)}&per_page=${limit}&sort=updated&order=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('GitHub involvement + topic search response:', data);
    console.log('Number of results:', data.items ? data.items.length : 0);
    
    // If we got results, return them
    if (data.items && data.items.length > 0) {
      return data.items;
    }
    
    // Fallback 1: get all repositories with the topic
    console.log('No direct results, trying fallback approach with topic search...');
    const topicResponse = await fetch(`${baseUrl}?q=topic:${topic.toLowerCase()}&per_page=${limit}&sort=updated&order=desc`);
    if (topicResponse.ok) {
      const topicData = await topicResponse.json();
      console.log('Topic search response:', topicData);
      
      // Filter repositories where user is the owner
      const ownerRepos = topicData.items ? topicData.items.filter(repo => 
        repo.owner && repo.owner.login === username
      ) : [];
      
      if (ownerRepos.length > 0) {
        console.log('Found owner repositories:', ownerRepos.length);
        return ownerRepos;
      }
    }
    
    // Fallback 2: get user's own repositories with keywords
    console.log('No topic results, trying user repositories with keywords...');
    const userRepos = await getRepositoriesByUser(username, [topic]);
    if (userRepos.length > 0) {
      console.log('Found user repositories:', userRepos.length);
      return userRepos;
    }
    
    console.log('No repositories found in any fallback');
    return [];
  } catch (error) {
    console.error('Error fetching repositories by involvement and topic:', error);
    return [];
  }
}

/**
 * Search repositories by user involvement (contributor or owner)
 * @param {string} username - GitHub username
 * @param {string|Array} keywords - Keyword(s) to filter
 * @param {number} limit - Maximum number of results
 * @returns {Promise<Array>} Array of repositories
 */
async function getRepositoriesByInvolvement(username, keywords, limit = 100) {
  const baseUrl = 'https://api.github.com/search/repositories';
  const keywordArray = Array.isArray(keywords) ? keywords : [keywords];
  
  try {
    // Build query: involves:username AND keyword
    const keywordQueries = keywordArray.map(kw => kw.toLowerCase()).join(' OR ');
    const query = `involves:${username} ${keywordQueries}`;
    
    const response = await fetch(`${baseUrl}?q=${encodeURIComponent(query)}&per_page=${limit}&sort=updated&order=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('GitHub involvement search response:', data);
    
    return data.items || [];
  } catch (error) {
    console.error('Error fetching repositories by involvement:', error);
    return [];
  }
}

/**
 * Search repositories in organizations
 * @param {string|Array} orgs - Organization name(s)
 * @param {string|Array} keywords - Keyword(s) to filter
 * @param {number} limit - Maximum number of results
 * @returns {Promise<Array>} Array of repositories
 */
async function getRepositoriesByOrganizations(orgs, keywords, limit = 100) {
  const baseUrl = 'https://api.github.com/search/repositories';
  const orgArray = Array.isArray(orgs) ? orgs : [orgs];
  const keywordArray = Array.isArray(keywords) ? keywords : [keywords];
  
  try {
    // Build query: org:orgname AND keyword
    const orgQueries = orgArray.map(org => `org:${org}`).join(' OR ');
    const keywordQueries = keywordArray.map(kw => kw.toLowerCase()).join(' OR ');
    const query = `(${orgQueries}) ${keywordQueries}`;
    
    const response = await fetch(`${baseUrl}?q=${encodeURIComponent(query)}&per_page=${limit}&sort=updated&order=desc`);
    if (!response.ok) {
      throw new Error(`GitHub API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('GitHub organization search response:', data);
    
    return data.items || [];
  } catch (error) {
    console.error('Error fetching repositories from organizations:', error);
    return [];
  }
}

/**
 * Format a single repository for display
 * @param {Object} repo - Repository object from GitHub API
 * @returns {HTMLElement} HTML element for the repository
 */
function formatRepositoryHTML(repo) {
  const name = repo.name || 'Untitled Repository';
  const description = repo.description || 'No description available';
  const url = repo.html_url || '#';
  const stars = repo.stargazers_count || 0;
  const language = repo.language || 'N/A';
  const updated = repo.updated_at ? new Date(repo.updated_at).toLocaleDateString() : 'N/A';
  
  const citationDiv = document.createElement('div');
  citationDiv.className = 'w3-padding-small';
  citationDiv.style.marginBottom = '12px';
  citationDiv.style.borderLeft = '3px solid #2e7d32';
  citationDiv.style.paddingLeft = '12px';
  
  const repoLink = `<a href="${url}" target="_blank" style="text-decoration: none; color: #2e7d32;">${url}</a>`;
  
  citationDiv.innerHTML = `
    <p style="margin: 4px 0; font-size: 14px; line-height: 1.6;">
      <strong>${name}</strong>. ${description}
    </p>
    <p style="margin: 4px 0; font-size: 12px; color: #555;">
      Language: ${language} | Stars: ${stars} | Updated: ${updated}
    </p>
    <p style="margin: 4px 0; font-size: 13px;">
      ${repoLink}
    </p>
  `;
  
  return citationDiv;
}

/**
 * Display repositories in a specified container
 * @param {string} containerId - ID of the container element
 * @param {string} username - GitHub username
 * @param {string|Array} keywords - Keyword(s) to filter
 */
async function displayRepositoriesByUser(containerId, username, keywords) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with ID '${containerId}' not found`);
    return;
  }
  
  // Show loading message
  container.innerHTML = '<p>Loading repositories from GitHub...</p>';
  
  try {
    const repos = await getRepositoriesByUser(username, keywords);
    
    if (repos && repos.length > 0) {
      container.innerHTML = ''; // Clear loading message
      repos.forEach(repo => {
        const repoDiv = formatRepositoryHTML(repo);
        container.appendChild(repoDiv);
      });
    } else {
      container.innerHTML = '<p>No repositories found with the specified keywords.</p>';
    }
  } catch (error) {
    console.error('Error displaying repositories:', error);
    container.innerHTML = '<p class="w3-text-red">Error loading repositories. Please try again later.</p>';
  }
}

/**
 * Display repositories by topic in a specified container
 * @param {string} containerId - ID of the container element
 * @param {string} topic - Topic to search for
 */
async function displayRepositoriesByTopic(containerId, topic) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with ID '${containerId}' not found`);
    return;
  }
  
  // Show loading message
  container.innerHTML = '<p>Loading repositories with topic "' + topic + '"...</p>';
  
  try {
    const repos = await getRepositoriesByTopic(topic);
    
    if (repos && repos.length > 0) {
      container.innerHTML = ''; // Clear loading message
      repos.forEach(repo => {
        const repoDiv = formatRepositoryHTML(repo);
        container.appendChild(repoDiv);
      });
    } else {
      container.innerHTML = '<p>No repositories found with the specified topic.</p>';
    }
  } catch (error) {
    console.error('Error displaying repositories:', error);
    container.innerHTML = '<p class="w3-text-red">Error loading repositories. Please try again later.</p>';
  }
}

/**
 * Display repositories from organizations in a specified container
 * @param {string} containerId - ID of the container element
 * @param {string|Array} orgs - Organization name(s)
 * @param {string|Array} keywords - Keyword(s) to filter
 */
async function displayRepositoriesByOrganizations(containerId, orgs, keywords) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with ID '${containerId}' not found`);
    return;
  }
  
  // Show loading message
  container.innerHTML = '<p>Loading repositories from organizations...</p>';
  
  try {
    const repos = await getRepositoriesByOrganizations(orgs, keywords);
    
    if (repos && repos.length > 0) {
      container.innerHTML = ''; // Clear loading message
      repos.forEach(repo => {
        const repoDiv = formatRepositoryHTML(repo);
        container.appendChild(repoDiv);
      });
    } else {
      container.innerHTML = '<p>No repositories found.</p>';
    }
  } catch (error) {
    console.error('Error displaying repositories:', error);
    container.innerHTML = '<p class="w3-text-red">Error loading repositories. Please try again later.</p>';
  }
}
