// HAL API Functions
// Documentation: https://api.archives-ouvertes.fr/docs
// Generated by VS Code Copilot, adapted for this project

/**
 * Fetch articles from HAL by author name
 * @param {string} authorName - The author name (e.g., 'Solenn Tual')
 * @param {number} startYear - Start year for publication date filter
 * @param {number} endYear - End year for publication date filter
 * @param {boolean} peerReviewedOnly - If true, only return peer-reviewed articles
 * @returns {Promise<Array>} Array of articles
 */
async function getArticlesByAuthor(authorName, startYear, endYear, peerReviewedOnly = true) {
  const baseUrl = 'https://api.archives-ouvertes.fr/search';
  
  // Build query: simple text search for author name, results are filtered by year in JavaScript
  const query = authorName;
  
  const params = new URLSearchParams({
    q: query,
    fl: 'docid,title_s,label_s,authFullName_s,publicationDate_s,conferenceTitle_s,uri_s,url_s,docType_s,proceedings_s,journalTitle_s,peerReview_s',
    wt: 'json',
    rows: 100,
    sort: 'publicationDate_s desc'
  });
  
  try {
    const response = await fetch(`${baseUrl}?${params}`);
    if (!response.ok) {
      throw new Error(`HAL API error: ${response.status}`);
    }
    
    const data = await response.json();
    console.log('HAL API response:', data);
    let articles = data.response?.docs || [];

    // Filter articles by year since the API doesn't support reliable year filtering
    articles = articles.filter(article => {
      if (!article.publicationDate_s) return false;
      // Extract year from date (format: YYYY-MM-DD or similar)
      const year = parseInt(article.publicationDate_s.split('-')[0]);
      return year >= startYear && year <= endYear;
    });
    // If peer-reviewed filter is enabled, filter articles accordingly
    if (peerReviewedOnly) {
      articles = articles.filter(article => article.proceedings_s === "1");
    }
    // Display the articles in the console
    console.log(articles);
    return articles;
  } catch (error) {
    console.error('Error fetching from HAL:', error);
    return [];
  }
}

/**
 * Format a single article for display
 * @param {Object} article - Article object from HAL API
 * @returns {string} HTML string for the article
 */
function formatArticleHTML(article) {
  const title = article.title_s || 'Untitled';
  const authors = Array.isArray(article.authFullName_s) 
    ? article.authFullName_s.join(', ') 
    : (article.authFullName_s || 'Unknown authors');
  const pubDate = article.publicationDate_s || 'Date unknown';
  const url = article.uri_s || article.url_s || '#';
  
  // Extract year from date for cleaner display
  const year = pubDate.split('-')[0] || pubDate;
  
  // Extract conference or journal name from label
  let conferenceOrJournal = '';
  if (article.label_s) {
    const label = article.label_s;
    // Try to extract conference name (between specific keywords)
    const conferenceMatch = label.match(/(?:International Conference|Conference|Workshop|Symposium|Colloque|Journée).*?(?:,|$)/i);
    const journalMatch = label.match(/(?:Journal|Revue).*?(?:,|\.|$)/i);
    
    if (journalMatch) {
      conferenceOrJournal = journalMatch[0].trim().replace(/[,.]$/, '');
    } else if (conferenceMatch) {
      conferenceOrJournal = conferenceMatch[0].trim().replace(/[,.]$/, '');
    }
  }
  
  // Fallback to explicit journal title if available
  if (!conferenceOrJournal && article.journalTitle_s) {
    conferenceOrJournal = article.journalTitle_s;
  }
  
  const citationDiv = document.createElement('div');
  citationDiv.className = 'w3-padding-small';
  citationDiv.style.marginBottom = '12px';
  citationDiv.style.borderLeft = '3px solid #2e7d32';
  citationDiv.style.paddingLeft = '12px';
  
  const halLink = `<a href="${url}" target="_blank" style="text-decoration: none; color: #2e7d32;">${url}</a>`;
  
  const journalOrConfPart = conferenceOrJournal ? ` <em>${conferenceOrJournal}.</em>` : '';
  
  citationDiv.innerHTML = `
    <p style="margin: 4px 0; font-size: 14px; line-height: 1.6;">
      <strong>${authors}</strong>. ${title}.${journalOrConfPart} ${year}. ${halLink}
    </p>
  `;
  
  return citationDiv;
}

/**
 * Display articles in a specified container
 * @param {string} containerId - ID of the container element
 * @param {string} authorId - The author ID
 * @param {number} startYear - Start year
 * @param {number} endYear - End year
 */
async function displayArticlesByAuthor(containerId, authorId, startYear, endYear) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with ID '${containerId}' not found`);
    return;
  }
  
  // Show loading message
  container.innerHTML = '<p>Loading articles from HAL...</p>';
  
  try {
    const articles = await getArticlesByAuthor(authorId, startYear, endYear);
    
    if (articles && articles.length > 0) {
      container.innerHTML = ''; // Clear loading message
      articles.forEach(article => {
        const citationDiv = formatArticleHTML(article);
        container.appendChild(citationDiv);
      });
      console.log(articles)
    } else {
      container.innerHTML = '<p>No articles found for the specified criteria.</p>';
    }
  } catch (error) {
    console.error('Error displaying articles:', error);
    container.innerHTML = '<p class="w3-text-red">Error loading articles. Please try again later.</p>';
  }
}
