// Zenodo API functions
// Generated by VS Code Copilot, adapted for this project

async function fetchZenodoDatasets() {
  const API_URL = 'https://zenodo.org/api/communities/19th_century-french-land-registry/records?size=50';
  
  try {
    const response = await fetch(API_URL);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const data = await response.json();
    // Filter for datasets only
    const datasets = (data.hits.hits || []).filter(record => 
      record.metadata?.resource_type?.type === 'dataset'
    );
    return datasets;
  } catch (error) {
    console.error('Error fetching Zenodo datasets:', error);
    return [];
  }
}

function formatAuthors(record) {
  const creators = record.metadata?.creators || [];
  if (creators.length === 0) return 'N/A';
  
  return creators
    .map(creator => {
      // Prefer given_name + family_name format (Firstname Lastname)
      if (creator.given_name && creator.family_name) {
        return `${creator.given_name} ${creator.family_name}`;
      }
      // If name field exists, try to format it as Firstname Lastname
      if (creator.name) {
        // If name contains comma, it's likely "Lastname, Firstname" - reformat it
        if (creator.name.includes(',')) {
          const parts = creator.name.split(',').map(p => p.trim());
          return parts.length === 2 ? `${parts[1]} ${parts[0]}` : creator.name;
        }
        return creator.name;
      }
      return 'Unknown Author';
    })
    .join(', ');
}

function formatDatasetName(record) {
  return record.metadata?.title || 'Untitled Dataset';
}

function formatDOI(record) {
  return record.metadata?.doi || (record.doi ? `https://doi.org/${record.doi}` : 'N/A');
}

function displayZenodoDatasets(datasets, containerId) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with id "${containerId}" not found`);
    return;
  }
  
  container.innerHTML = ''; // Clear previous content
  
  if (datasets.length === 0) {
    container.innerHTML = '<p>No datasets found.</p>';
    return;
  }
  
  datasets.forEach(dataset => {
    const authors = formatAuthors(dataset);
    const name = formatDatasetName(dataset);
    const doi = formatDOI(dataset);
    const zenodoUrl = `https://zenodo.org/records/${dataset.id}`;
    
    const citationDiv = document.createElement('div');
    citationDiv.className = 'w3-padding-small';
    citationDiv.style.marginBottom = '12px';
    citationDiv.style.borderLeft = '3px solid #2e7d32';
    citationDiv.style.paddingLeft = '12px';
    
    const doiLink = doi !== 'N/A' && doi.startsWith('http')
      ? `<a href="${doi}" target="_blank" style="text-decoration: none; color: #2e7d32;">${doi}</a>`
      : `<span>${doi}</span>`;
    
    const zenodoLink = `<a href="${zenodoUrl}" target="_blank" style="text-decoration: none; color: #2e7d32;">${zenodoUrl}</a>`;
    
    citationDiv.innerHTML = `
      <p style="margin: 4px 0; font-size: 14px; line-height: 1.6;">
        <strong>${authors}</strong>. ${name}. ${doiLink}. ${zenodoLink}
      </p>
    `;
    
    container.appendChild(citationDiv);
  });
}

// Load Zenodo datasets
async function initializeZenodoDatasets() {
  const resultsDiv = document.getElementById('resultsDatasets');
  
  if (!resultsDiv) {
    console.warn('resultsDatasets container not found');
    return;
  }
  
  try {
    // Show loading message
    resultsDiv.innerHTML = '<p>Loading datasets from Zenodo...</p>';
    
    // Fetch datasets
    const datasets = await fetchZenodoDatasets();
    
    // Display datasets
    displayZenodoDatasets(datasets, 'resultsDatasets');
  } catch (error) {
    console.error('Error loading Zenodo datasets:', error);
    resultsDiv.innerHTML = '<p class="w3-text-red">Error loading datasets. Please try again later.</p>';
  }
}

// Initialize when DOM is ready or immediately if already loaded
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    initializeZenodoDatasets();
    initializeZenodoModels();
  });
} else {
  initializeZenodoDatasets();
  initializeZenodoModels();
}

async function fetchZenodoModels() {
  const API_URL = 'https://zenodo.org/api/communities/19th_century-french-land-registry/records?size=50';
  
  try {
    const response = await fetch(API_URL);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const data = await response.json();
    // Filter for models only
    const models = (data.hits.hits || []).filter(record => 
      record.metadata?.resource_type?.type === 'model'
    );
    return models;
  } catch (error) {
    console.error('Error fetching Zenodo models:', error);
    return [];
  }
}

function displayZenodoModels(models, containerId) {
  const container = document.getElementById(containerId);
  if (!container) {
    console.error(`Container with id "${containerId}" not found`);
    return;
  }
  
  container.innerHTML = ''; // Clear previous content
  
  if (models.length === 0) {
    container.innerHTML = '<p>No models found.</p>';
    return;
  }
  
  models.forEach(model => {
    const authors = formatAuthors(model);
    const name = formatDatasetName(model);
    const doi = formatDOI(model);
    const zenodoUrl = `https://zenodo.org/records/${model.id}`;
    
    const citationDiv = document.createElement('div');
    citationDiv.className = 'w3-padding-small';
    citationDiv.style.marginBottom = '12px';
    citationDiv.style.borderLeft = '3px solid #2e7d32';
    citationDiv.style.paddingLeft = '12px';
    
    const doiLink = doi !== 'N/A' && doi.startsWith('http')
      ? `<a href="${doi}" target="_blank" style="text-decoration: none; color: #2e7d32;">${doi}</a>`
      : `<span>${doi}</span>`;
    
    const zenodoLink = `<a href="${zenodoUrl}" target="_blank" style="text-decoration: none; color: #2e7d32;">${zenodoUrl}</a>`;
    
    citationDiv.innerHTML = `
      <p style="margin: 4px 0; font-size: 14px; line-height: 1.6;">
        <strong>${authors}</strong>. ${name}. ${doiLink}. ${zenodoLink}
      </p>
    `;
    
    container.appendChild(citationDiv);
  });
}

// Load Zenodo models
async function initializeZenodoModels() {
  const resultsDiv = document.getElementById('resultsModels');
  
  if (!resultsDiv) {
    console.warn('resultsModels container not found');
    return;
  }
  
  try {
    // Show loading message
    resultsDiv.innerHTML = '<p>Loading models from Zenodo...</p>';
    
    // Fetch models
    const models = await fetchZenodoModels();
    
    // Display models
    displayZenodoModels(models, 'resultsModels');
  } catch (error) {
    console.error('Error loading Zenodo models:', error);
    resultsDiv.innerHTML = '<p class="w3-text-red">Error loading models. Please try again later.</p>';
  }
}
